// Licensed under CC-BY-4.0 (<https://creativecommons.org/licenses/by/4.0/>)

= NNA Roadmap
Mars <mars@squirrel.pub>
v0.0.0
:homepage: https://github.com/emperorofmars/nna
:keywords: nna, 3d, fbx, extension, fileformat, format, interchange, interoperability
:hardbreaks-option:
:library: Asciidoctor
:toc:
:toclevels: 1
:toc-placement!:
:idprefix:
:idseparator: -
:experimental:
:table-caption!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

link:./readme.adoc[Home] 🔶 link:./nna_spec.adoc[NNA Core Spec] 🔶 link:./nna_component_types.adoc[NNA Component Types] 🔶 Roadmap

toc::[]


== Current Status
The structure is pretty much there, and specific functionality is being worked on.


== Stage 1: MVP
Parse decently featured VR avatars from `*.nna.fbx` files in Unity. Some resources like animator controllers or materials will be mapped by name from the Unity project.

Have a decent Blender extension to create NNA definitions with a GUI.

The 'export from Blender, drag into Unity, and get a ready to upload VR avatar' experience is generally there, but the file depends on resources in the Unity project.

=== TODO
* NNA Core
	** Rotation Constraints


== Stage 2: All In One
An `*.nna.fbx` file no longer needs external dependencies, other than NNA itself, in order to be parsed into a fully featured VR avatar in a game-engine.

A lot of these features are blocked by Blender's (lack of an) animation system. Will be fixed once Blender 4.4 is released with 'slotted actions'.

=== TODO
* NNA Core
	** More constraint types (Position, Parent, Lookat, Aim)
	** Animations, including being able to target NNA properties. (Blocked until Blender 4.4)
	** Implement https://github.com/emperorofmars/stf-unity/tree/master/MTF[MTF] to fully encode shader & game engine agnostic materials.
* More VR & V-tubing avatar components & features
	** Bone physics (fully develop ava.secondary_motion as an universal fallback, DynamicBones, maybe MagickaCloth)
	** Automatic animator controller generation (Partially blocked until Blender 4.4)
		*** Face Tracking
		*** Hand gestures (additionally: fallback VRM blendshape pose nonsense)
		*** Toggles
		*** Joystick puppets
		*** Custom application & game engine agnostic animation logic
	** Option to automatically generate a shadow rig for the fingers with a constraint based setup to animate the actual finger bones, unless VRChat fixes this bug: https://feedback.vrchat.com/avatar-30/p/finger-muscle-settings


== Stage 3: Overlord
Go beyond what VR & V-Tubing applications support out of the box.

=== TODO
* Template system. (To apply user modifications. This would be the basis of a 'character editor' system, so end users could adapt their avatars easier.)
	** Hand-gesture rebinding
	** Sliders & toggles for ahead-of-time avatar customization
	** Easy texture swapping utility
* Asset-Addon system. (To apply a piece of clothing from a separate file to a base body for example. This should be deeply integrated with the avatar components and the template system.)
* IK components
* IDK, suggest me more!
